OnlineBakery/Controllers/CartController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineBakery.Models;

namespace OnlineBakery.Controllers
{
  [Authorize]
  public class CartController : Controller
  {
    private readonly OnlineBakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public CartController(UserManager<ApplicationUser> userManager, OnlineBakeryContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    
    // Index *****************
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var model = _db.Carts.Where(entry => entry.User.Id == currentUser.Id).OrderBy(entry => entry.OrderId).ToList();
      return View(model);
    }
    // New Cart ****************
    public async Task<ActionResult> Create()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Cart> userCart = _db.Carts.Where(y => y.User.Id == currentUser.Id && y.OrderId == 0).ToList();
      if (userCart.Any())
      {
        ViewBag.Cart = userCart;
      }
      ViewBag.ClientId = currentUser.Id;
      List<FlavorTreat> model = _db.FlavorTreat.OrderBy(x => x.FlavorId).ToList();
      return View(model);
    }
    // AddToCart
    public async Task<ActionResult> AddToCart(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      _db.Carts.Add(new Cart {FlavorTreatId = id, OrderId = 0, Quantity = 0, User = currentUser});
      _db.SaveChanges();
      return RedirectToAction("Create");
    }
    // DeleteItem
    public ActionResult DeleteItem(int id)
    {
      var thisCart = _db.Carts.FirstOrDefault(cart => cart.CartId == id);
      _db.Carts.Remove(thisCart);
      _db.SaveChanges();
      return RedirectToAction("Create");
    }
    
    public ActionResult ChangeItem(int id, int qty)
    {
      if(qty >= 0)
      {
        var cart = new Cart { CartId = id, Quantity = qty };
        _db.Carts.Attach(cart);
        _db.Entry(cart).Property(x => x.Quantity).IsModified = true;
        _db.SaveChanges();
      }
      return RedirectToAction("Create");
    }
    // BuyCart
    public async Task<ActionResult> BuyCart()
    {
      int order = _db.Carts.Select(x => x.OrderId).DefaultIfEmpty(0).Max();
      order++;
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Cart> userCart = _db.Carts.Where(y => y.User.Id == currentUser.Id && y.OrderId == 0).ToList();
      foreach(Cart item in userCart)
      {
        item.OrderId = order;
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = order});
    }
    // Details **************
    public async Task<ActionResult> Details(int id)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Cart> model = _db.Carts.Where(y => y.User.Id == currentUser.Id && y.OrderId == id).ToList();
      return View(model);
    }
  }
}

OnlineBakery/Controllers/FlavorsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineBakery.Models;


namespace OnlineBakery.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly OnlineBakeryContext _db;
    public FlavorsController(OnlineBakeryContext db)
    {
      _db = db;
    }
    // Index *****************
    public ActionResult Index()
    {
      List<Flavor> model = _db.Flavors.OrderBy(x => x.Name).ToList();
      return View(model);
    }
    // Create ****************
    public ActionResult Create()
    {
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Flavor flavor, int TreatId)
    {
      _db.Flavors.Add(flavor);
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    // Details **************
    public ActionResult Details(int id)
    {
      Flavor model = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(model);
    }
    // Delete ******************
    public ActionResult Delete(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      return View(thisFlavor);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(x => x.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteTreat(int joinId, int FlavorId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = FlavorId });
    }
    // Edit **************
    public ActionResult Edit(int id)
    {
      var thisFlavor = _db.Flavors.FirstOrDefault(flavors => flavors.FlavorId == id);
      var thisFlavorTreat = _db.FlavorTreat.FirstOrDefault(x => x.FlavorId == thisFlavor.FlavorId);
      if(thisFlavorTreat != null)
      {
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name", thisFlavorTreat.TreatId);
      }
      else
      {
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      }
      return View(thisFlavor);
    }
    [HttpPost]
    public ActionResult Edit(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        bool tf = _db.FlavorTreat.Any(x => x.FlavorId == flavor.FlavorId && x.TreatId == TreatId);
        if (!tf)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
        }
      }
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

OnlineBakery/Controllers/ManageUsersController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using OnlineBakery.Models;
using OnlineBakery.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace OnlineBakery.Controllers
{
    [Authorize(Roles = Constants.AdministratorRole)]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<ApplicationUser>
            _userManager;

        public ManageUsersController(
            UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var admins = (await _userManager
                .GetUsersInRoleAsync("Administrator"))
                .ToArray();

            var everyone = await _userManager.Users
                .ToArrayAsync();

            var model = new ManageUsersViewModel
            {
                Administrators = admins,
                Everyone = everyone
            };

            return View(model);
        }
    }
}

OnlineBakery/Controllers/TreatsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineBakery.Models;


namespace OnlineBakery.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly OnlineBakeryContext _db;
    public TreatsController(OnlineBakeryContext db)
    {
      _db = db;
    }
    // Index *****************
    public ActionResult Index()
    {
      List<Treat> model = _db.Treats.OrderBy(treat => treat.Name).ToList();
      return View(model);
    }
    // Create ****************
    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Treat treat, int FlavorId)
    {
      _db.Treats.Add(treat);
      if (FlavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    // Details **************
    public ActionResult Details(int id)
    {
      Treat model = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(model);
    }
    // Delete ******************
    public ActionResult Delete(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult DeleteFlavor(int joinId, int TreatId)
    {
      var joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = TreatId });
    }
    // Edit **************
    public ActionResult Edit(int id)
    {
      var thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      var thisFlavorTreat = _db.FlavorTreat.FirstOrDefault(x => x.TreatId == thisTreat.TreatId);
      if(thisFlavorTreat != null)
      {
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name", thisFlavorTreat.FlavorId);
      }
      else
      {
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
      }
      return View(thisTreat);
    }
    [HttpPost]
    public ActionResult Edit(Treat treat, int FlavorId)
    {
      if (FlavorId != 0)
      {
        bool tf = _db.FlavorTreat.Any(x => x.FlavorId == FlavorId && x.TreatId == treat.TreatId);
        if (!tf)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = FlavorId, TreatId = treat.TreatId });
        }
      }
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

OnlineBakery/Views/Shared/Footer.cshtml
<div id="footer">
  <p>This site is only an example project for <a href="https://www.epicodus.com/">Epicodus</a></p>
</div>

OnlineBakery/Views/Shared/Header.cshtml
@using Microsoft.AspNetCore.Identity
@using OnlineBakery.Models

@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<div id="header">
  <p>Pierre's Online Bakery</p>
  <div class="std-btn">
    @if (signInManager.IsSignedIn(User))
    {
      var currentUser = await userManager.GetUserAsync(User);
      var isAdmin = currentUser != null
          && await userManager.IsInRoleAsync(
              currentUser,
              Constants.AdministratorRole);

      if (isAdmin)
      {
        @Html.ActionLink(" Treats", "Index", "Treats", null, new { @class = "btn btn-info fa fa-gear"})
        @Html.ActionLink(" Flavors", "Index", "Flavors", null, new { @class = "btn btn-info fa fa-gear"})
        @Html.ActionLink(" Manage Users", "Index", "ManageUsers", null, new { @class = "btn btn-info fa fa-gear"})
      }
      else
      {
        @Html.ActionLink(" History", "Index", "Cart", null, new {@class = "btn btn-info fa fa-th-list"})
        @Html.ActionLink(" New Cart", "Create", "Cart", null, new {@class = "btn btn-info fa fa-shopping-cart"})
      }
    }
  </div>
  <div class="userinfo">
    @if (User.Identity.IsAuthenticated)
    {
      @User.Identity.Name
      @Html.ActionLink(" Log Off", "Index","Account", null, new { @class = "btn btn-info fa fa-sign-out"})
    }
    else
    {
      @Html.ActionLink(" Log in", "Login", "Account", null, new { @class = "btn btn-info fa fa-sign-in" })
      @Html.ActionLink(" Register", "Register", "Account", null, new {@class = "btn btn-info fa fa-pencil-square-o"})
    }
  </div>
</div>

OnlineBakery/Views/Shared/_Footer.cshtml
<div id="footer">
  <p>This site is only an example project for <a href="https://www.epicodus.com/">Epicodus</a></p>
</div>

OnlineBakery/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using OnlineBakery.Models

@inject SignInManager<ApplicationUser> signInManager
@inject UserManager<ApplicationUser> userManager

<div id="header">
  <p>Pierre's Online Bakery</p>
  <div class="std-btn">
    @if (signInManager.IsSignedIn(User))
    {
      var currentUser = await userManager.GetUserAsync(User);
      var isAdmin = currentUser != null
          && await userManager.IsInRoleAsync(
              currentUser,
              Constants.AdministratorRole);

      if (isAdmin)
      {
        @Html.ActionLink(" Treats", "Index", "Treats", null, new { @class = "btn btn-info fa fa-gear"})
        @Html.ActionLink(" Flavors", "Index", "Flavors", null, new { @class = "btn btn-info fa fa-gear"})
        @Html.ActionLink(" Manage Users", "Index", "ManageUsers", null, new { @class = "btn btn-info fa fa-gear"})
      }
      else
      {
        @Html.ActionLink(" History", "Index", "Cart", null, new {@class = "btn btn-info fa fa-th-list"})
        @Html.ActionLink(" New Cart", "Create", "Cart", null, new {@class = "btn btn-info fa fa-shopping-cart"})
      }
    }
  </div>
  <div class="userinfo">
    @if (User.Identity.IsAuthenticated)
    {
      @User.Identity.Name
      @Html.ActionLink(" Log Off", "LogOut", "Account", null, new { @class = "btn btn-info fa fa-sign-out"})
    }
    else
    {
      @Html.ActionLink(" Log in", "Login", "Account", null, new { @class = "btn btn-info fa fa-sign-in" })
      @Html.ActionLink(" Register", "Register", "Account", null, new {@class = "btn btn-info fa fa-pencil-square-o"})
    }
  </div>
</div>

OnlineBakery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Online Bakery</title>
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
  <link rel="stylesheet" href="~/css/styles.css"> 
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <div class="container">
    @await Html.PartialAsync("_Header")
    <div id="render">
      @RenderBody()
    </div>
    @Html.Partial("_Footer")
  </div>
</body>

</html>